server:
  port: 1314
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    max-swallow-size: -1
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 10S
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bill?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      filter:
        wall:
          config:
            multi-statement-allow: true
    hikari:
      max-lifetime: 60000
      maximum-pool-size: 1000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  # Redis
  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
    timeout: 3S
  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false

captcha:
  # 图片验证码验证
  image:
    - /zwz/login # 登录接口
    - /zwz/oauth2/authorize # 认证接口
  # 短信验证码验证
  sms:
    - /zwz/user/regist # 注册接口
    - /zwz/user/smsLogin # 短信登录接口
    - /zwz/user/resetByMobile # 手机重置密码
    - /zwz/user/changeMobile # 更换绑定手机
    - /zwz/app/v1/member/quickLogin # 会员快捷登录注册接口
  # Vaptcha验证码验证
  vaptcha:
    - /zwz/common/captcha/sendRegistSms/** # 发送注册短信
    - /zwz/common/captcha/sendResetSms/** # 发送重置密码短信
    - /zwz/email/sendResetCode/** # 发送重置密码邮件
    - /zwz/social/relate # 绑定第三方账号
  # Email验证码验证
  email:
    - /zwz/email/resetByEmail # 邮件重置密码
    - /zwz/email/editEmail # 修改绑定邮箱

# 忽略url
ignored:
  urls:
    - /zwz/**/**
    - /zwz/app/v1/**
    - /zwz/oauth2/**
    - /zwz/actuator/**
    - /zwz/admin/**
    - /editor-app/**
    - /zwz/act/**
    - /zwz/dictData/getByType/**
    - /zwz/email/sendResetCode/**
    - /zwz/email/resetByEmail
    - /zwz/file/view/**
    - /zwz/social/**
    - /zwz/ws/**
    - /zwz/setting/notice
    - /zwz/user/regist
    - /zwz/user/smsLogin
    - /zwz/user/resetByMobile
    - /zwz/common/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /zwz/test/**
  # 限流及黑名单不拦截的路径
  limitUrls:
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico

# Actuator
management:
  health:
    elasticsearch:
      enabled: false
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          DOWN: 200
          OUT_OF_SERVICE: 200
          FATAL: 200
          UNKNOWN: 200
  endpoints:
    web:
      base-path: /zwz/actuator/
      exposure:
        include: '*'

# Swagger界面内容配置
swagger:
  title: 超市账单管理系统
  description: 超市账单管理系统接口文档
  version: 1.0.0
  termsOfServiceUrl: http://zwz.cn
  contact:
    name: 郑为中
    url: http://zwz.cn
    email: 916077357@qq.com

# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

# 日志
logging:
  # 输出级别
  level:
    root: info
  file:
    # 指定路径
    path: logs
    # 最大保存天数
    max-history: 7
    # 每个文件最大大小
    max-size: 5MB